name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # 此处使用您的主分支名称

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Set Timestamp as Tag
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y%m%d')"
        
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: docker build -t ddv12138/data-backup:${{ steps.timestamp.outputs.timestamp }} .

      - name: Push Docker Image
        run: docker push ddv12138/data-backup:${{ steps.timestamp.outputs.timestamp }}
